commStation_main/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),

    path ('marketplace/', include('marketplace.urls')),

    #cart page
    path('cart/', MarketplaceViews.cart, name='cart'),

    #search path 
    path('search/', MarketplaceViews.search, name='search'),

    #checkout
    path('checkout/', MarketplaceViews.checkout, name= 'checkout' ),

    #ordering
    path('orders/', include('orders.urls')),
         
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_complete/', views.order_complete, name='order_complete'),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User
from django.db.models.fields.related import OneToOneField
from django.templatetags.static import static

from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point
# from geopy.geocoders import Nominatim
# from django.contrib.gis.geos import fromstr




# Create your models here.
#only contains methods for creating users https://docs.djangoproject.com/en/4.2/topics/db/examples/one_to_one/
from django.contrib.auth.models import BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must enter an email address')
        
        if not username:
            raise ValueError('User must enter a username')
        
        user = self.model (
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('Superuser must enter an email address')
        
        if not username:
            raise ValueError('Superuser must enter a username')
        
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


#this is for the super user
class User(AbstractBaseUser):
    BUSINESS = 1
    CUSTOMER = 2
    #USER = 3

    ROLE = (
        (BUSINESS, 'Business'),
        (CUSTOMER, 'Customer'),
        #(USER, 'user')

    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_Number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE, blank=True, null=True)

    #required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modifed_date = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True
    def get_role(self):
        if self.role == 1:
            user_role = "Business"
        elif self.role == 2:
            user_role = 'Customer'
        return user_role
    
class userProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='user/profile_pictures',  blank=True, null=True)
    cover_photo = models.ImageField(upload_to='users/cover_photos',  blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    post_code = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    staff_code = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def get_cover_photo_url(self):
        if self.cover_photo and hasattr(self.cover_photo, 'url'):
            return self.cover_photo.url
        
    def get_profile_picture_url(self):
        if self.profile_picture and self.profile_picture.name != '':
            return self.profile_picture.url 
        return None

    def __str__(self):
        return self.user.email
    #add the location map for the searhc function in the backend from geolocation api https://docs.djangoproject.com/en/4.2/ref/contrib/gis/db-api/
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
            return super(userProfile, self).save(*args, **kwargs)
        return super(userProfile, self).save(*args, **kwargs)
    
  

#post_save.connect(post_save_create_profile_receiver, sender=User) using singals https://docs.djangoproject.com/en/4.2/ref/signals/

orders/models.py
import json
from django.db import models
from accounts.models import User
from menu.models import menuItem
from business.models import Business

request_object = ''

# Create your models here.
class Payment(models.Model):
    PAYMENT_METHOD =(
        ('Paypal', 'Paypal'),
        ('Stripe','Stripe')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id
    
class Order(models.Model):
    STATUS =(
        ('New','New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'), 
        ('Cancelled', 'Cancelled'), 
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    businesses = models.ManyToManyField(Business,blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=12, blank=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    post_code = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text= "Data format: {'service_type':{'service_percentage':'tax_amount'}}",null=True)
    total_data = models.JSONField(blank=True, null=True)
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def order_placed_to(self):
        return ", ".join([str(i) for i in self.businesses.all()])
    
    def get_total_by_business(self):
        business = Business.objects.get(user=request_object.user)
        if self.total_data:
            total_data = json.loads(self.total_data)
            data = total_data.get(str(business.id))
            print(data)
        return business
    
    def __str__(self):
        return self.order_number
    
class OrderedItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    menuitem = models.ForeignKey(menuItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.menuitem.menu_title

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Comm Station Online Restaurant</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %} " rel="stylesheet">

	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{%static 'js/modernizr.js' %}"></script>
	<script src="{%static 'js/bootstrap.js'%}"></script>
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<script src="https://kit.fontawesome.com/c03014cf4f.js" crossorigin="anonymous"></script>

	<!-- Script to load in HTML head Google Mpa platform---> 
	<!-- remove HTML console error -->
	{% if '/' == request.path or 'profile' in request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}&libraries=places&callback=initAutoComplete" defer></script>
	{% endif %}
	
	<!-- install sweetalert -->
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="{% static 'js/custom.js' %}"></script>

	
	<!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=EUR"></script>



	<!-- Jstyle tags -->
	<style>
		body,
		.main-section p,
		.mce-content-body p {
			font: Normal 14px/24px "Open Sans", sans-serif;
			letter-spacing: 0px;
			text-transform: none;
			color: #515151 !important;
		}
	</style>

</head>

<body>
	<!--Navbar-->
	{% include 'includes/navbar.html' %}

	<!--add content here for user page-->
	{% block content %}

	{% endblock %}

	<!--Footer-->
	{% include 'includes/footer.html' %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Main Wrapper
<div class="wrapper"> -->

	<!-- Main Section Start -->
	<div class="main-section">
		<!-- Home Pages Elements Strat -->
		<!-- Main Search Start -->
		<div class="page-section nopadding cs-nomargin"
			style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/food-2.jpg' %}) no-repeat center / cover;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="element-title">
							<h1
								style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
								Any service, Any Time <br>from any local business</h1>
							<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
								Ridiculus sociosqu
								cursus neque cursus curae ante scelerisque vehicula.</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="main-search fancy bg-holder">
							<form action ="{% url 'search' %}" method ="GET">
								<div class="row">
									<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
										<div class="field-holder">
											<input type="text" name="search_word" placeholder="Business name or Service ">
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
										<div class="field-holder">
											<ul>
												<li class="select-location">
													<div class="foodbakery-locations-fields-group foodbakery-focus-out">
														<span class="foodbakery-search-location-icon"><i
																class="icon-location"></i></span>
														

														<input type="text" name = "address" class="location-field-text filter" id="id_address" required
															placeholder="All Locations" >
														<input type="hidden" name="lat" value="" id="id_latitude"> 
														<input type="hidden" name="lng" value="" id="id_longitude"> 
															
													</div>
													
												</li>
											</ul>
										</div>
									</div>
									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<select name="radius" id="radius" style ="height: 50px;" required>
											<option value="">Choose Radius </option>
											<option value="5">5km</option>
											<option value="10">10km</option>
											<option value="15">15km</option>
											<option value="20">20km</option>
											<option value="50">50km</option>
										</select>

									</div>


									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<div class="field-holder">
											<input type="submit" value="Search">
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- Main Search End -->

		<!-- Top Restarurants Section Start -->
		<div class="page-section nopadding cs-nomargin"
			style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-left">
							<h2>Top Services</h2>
							<p>Explore local businesses and services. Support Local!</p>
							
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style ="padding-right: 0 !important; padding-right: 0 !important";>
						<div class="company-logo">
							<ul>
								{% for business in businesses %}
								<li class="has-border">
									<figure>
										{% if business.user_profile.profile_picture %}
										<a href="{% url 'business_detail' business.bus_slug %}"><img src="{{ business.user_profile.profile_picture.url }}"
												class="attachment-full size-full wp-post-image" alt=""></a>
										{% else %}
										<a href="{% url 'business_detail' business.bus_slug %}"><img src="{% static 'extra-images/default_profile_image.jpg' %}"
											class="attachment-full size-full wp-post-image" alt=""></a>

										{% endif %}
									</figure>
								</li>
								{% endfor %}

								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Restarurants Section End -->
		<!-- Choose From Most Popular Listin Start -->
		<div class="page-section nopadding cs-nomargin"
			style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-center">
							<h2>Choose From Most Popular Restaurants</h2>
							<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="listing fancy">
							<ul class="row">
								{% for business in businesses %}

								<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
									<div class="list-post featured">
										<div class="img-holder">
											<figure>

												<a href="{% url 'business_detail' business.bus_slug %}">
													{% if business.user_profile.profile_picture %}
													<img src="{{ business.user_profile.profile_picture.url }}"
														class="img-thumb wp-post-image" alt="">
													{% else %}
													<img src="{% static 'extra-images/default_profile_image.jpg' %}"
														class="img-thumb wp-post-image" alt="">
													{% endif %}
													</a>
													</figure>
											{% if business.is_open %}		
											<span class="restaurant-status open">
												<em class="bookmarkRibbon"></em>Open
											</span>
											{% else %}
											<span class="restaurant-status close">
												<em class="bookmarkRibbon"></em>Closed
											</span>
											{% endif %}

										</div>


										<div class="text-holder">
											
											<div class="post-title">
												<h5>
													<a href="listing-detail.html">{{ business }}</a>
													
												</h5>
											</div>
											{% if business.user_profile.city and business.user_profile.country and business.user_profile.post_code %}
											<span>{{ business.user_profile.city }}, {{ business.user_profile.country }}, {{ business.user_profile.post_code }}</span>
											{% endif %}

											{% if business.kms %}
											<br>
											<span><small><b>{{ business.kms }} km</b>away </small></span>
											{% endif %}

										</div>

									</div>
								</li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Choose From Most Popular Listing End -->

		<!-- Home Pages Elements End  -->
	</div>
	<!-- Main Section End -->

	{% endblock %}